version: "1.0"

services:
  postgres:
    image: postgres
    volumes:
      - ./.postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_READER_CONNECTION=""
      - POSTGRES_WRITER_CONNECTION=""