pipeline:

#  binancelive:
#    timeframe: 1m
#    pair: ETHUSDT
  csvfile:
    path: testdata/GOOG.csv
    schema:
      Date: dateiso
      Open: number
      High: number
      Low: number
      Close: number
      Adj Close: number
      Volume: number
  backtest:
    strategy: macdcross